name: "ECS Deploy"
description: "Create a new task definition version and update the service"
author: The Cloud Connectors
inputs:
  cluster:
    description: "The name of the ECS cluster"
    required: true
  service:
    description: "The name of the ECS service"
    required: true
  task-definition:
    description: "The name of the existing task definition to update"
    required: true
  image:
    description: "The new image URI to deploy"
    required: true
  region:
    description: "AWS region"
    required: false
    default: "us-east-2"
runs:
  using: docker
  image: Dockerfile